credentials:
  existingSecret: cloud-credentials
  useSecret: true
  name: cloud-credentials
  key: cloud

configuration:
  features: EnableCSI
  backupStorageLocation:
    - name: default
      provider: azure
      bucket: velero
      config:
        resourceGroup: hamza-resources
        storageAccount: velerobackupkalech
        storageAccountKeyEnvVar: AZURE_STORAGE_ACCOUNT_ACCESS_KEY

  volumeSnapshotLocation:
    - name: default
      provider: azure
      config:
        resourceGroup: MC_hamza-resources_hamzaDevOps_eastus
        subscriptionId: **
        apiTimeout: 5m
        incremental: true

snapshotsEnabled: true

initContainers:
  - name: velero-plugin-for-microsoft-azure
    image: velero/velero-plugin-for-microsoft-azure:v1.9.0
    volumeMounts:
      - name: plugins
        mountPath: /target


env:
  VELERO_FEATURES: EnableCSI
