apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: daily-backup
  namespace: velero
spec:
  schedule: "0 2 * * *"     # Run every day at 2 AM UTC
  template:
    ttl: 168h               # Retain backups for 7 days
    includedNamespaces:
      - hamzadevops
    snapshotVolumes: true
